import time
import os

print('Inicializando IA - AUDITOR')

time.sleep(5)
for i in range(3):
    os.system('cls')
    print('Inicializando IA - AUDITOR')
    print(f'Carregando instruções.')
    time.sleep(0.5)
    os.system('cls')
    print('Inicializando IA - AUDITOR')
    print(f'Carregando instruções..')
    time.sleep(0.5)
    os.system('cls')
    print('Inicializando IA - AUDITOR')
    print(f'Carregando instruções...')
    time.sleep(0.5)

for i in range(4):
    os.system('cls')
    print('Inicializando IA - AUDITOR')
    print(f'Instruções carregadas')
    print(f'Carregando base de dados.')
    time.sleep(0.5)
    os.system('cls')
    print('Inicializando IA - AUDITOR')
    print(f'Instruções carregadas')
    print(f'Carregando base de dados..')
    time.sleep(0.5)
    os.system('cls')
    print('Inicializando IA - AUDITOR')
    print(f'Instruções carregadas')
    print(f'Carregando base de dados...')
    time.sleep(0.5)


os.system('cls')
time.sleep(2)
print('Sistema inicializado com sucesso')
time.sleep(2)
print('Status: ONLINE')
time.sleep(2)
os.system('cls')
print('')
print(' -----------------------------------------------------')
print('|      SEJA BEM VINDO AO "AUDITOR"  -  CGA 2024       |')
print('| ----------------------------------------------------|')
print(f'| Seção de Banco de Dados e Controle de Qualidade     |')
print(f'| Para iniciar busca por inconsistências pressione F1 |')
print(f'| Para acessar as auditorias geradas, pressione F2    |')
print(f'|                       -*-                           |')
print(' -----------------------------------------------------', end='\r\n')
time.sleep(10)
